# Application Information
# ~~~~~
application.name = Axelor DEMO
application.description = The Demo Application
application.version = 8.0.0

# Author/Company
# ~~~~~
application.author = Axelor
application.copyright = Copyright (c) {year} Axelor. All Rights Reserved.

# Home Website
# ~~~~~
# Link to be used with header logo
application.home = https://www.axelor.com

# Link to the online help
# ~~~~~
application.help = https://docs.axelor.com

# Application deployment mode
# ~~~~~
# Set to 'dev' for development mode else 'prod'
application.mode = dev

# CSS Theme
# ~~~~~
# Set default CSS theme, for example `blue`
application.theme = auto

# Default Locale (language)
# ~~~~~
# Set default application locale (en, fr, fr_FR, en_US)
application.locale =

# Sign-in page configuration
# ~~~~~

# Sign-in title
application.sign-in.title = <h3>Welcome to the demo app</h3>

# Sign-in footer
application.sign-in.footer = <div style="width: 100%; text-align: left;">&#x2754; Demo App is based on <a href="https://github.com/axelor/axelor-open-platform">Axelor Open Platform</a> <br/>\
  &#x1F440; Need info? Browse the <a href="https://docs.axelor.com/adk">documentation</a></div>

# Encryption
# ~~~~~
# Set encryption password
encryption.password = MySuperSecretKey

# Set encryption algorithm (CBC or GCM)
encryption.algorithm = CBC

# Database settings
# ~~~~~
# See hibernate documentation for connection parameters

# PostgreSQL
db.default.driver = org.postgresql.Driver
#db.default.ddl = update
db.default.ddl = create-drop
db.default.url = jdbc:postgresql://localhost:5432/axelor
db.default.user = axelor
db.default.password = axelor

# Shared cache mode settings
# ~~~~~
jakarta.persistence.sharedCache.mode = ENABLE_SELECTIVE

# HikariCP connection pool
# ~~~~~
hibernate.hikari.minimumIdle = 5
hibernate.hikari.maximumPoolSize = 20
hibernate.hikari.idleTimeout = 300000

# Session timeout (in minutes)
# ~~~~~
session.timeout = 60

# Storage path for upload files (attachments)
# ~~~~~
# use {user.home} key to save files under user home directory, or
# use absolute path where server user have write permission.
data.upload.dir = {user.home}/.axelor/attachments

# Maximum upload size (in MB)
# ~~~~~
data.upload.max-size = 5

# The external report design directory
# ~~~~~
# this directory is searched for the rptdesign files
# (fallbacks to designs provided by modules)
reports.design-dir = {user.home}/.axelor/reports

# Storage path for report outputs
reports.output-dir = {user.home}/.axelor/reports-gen

# Data export (csv) encoding
# ~~~~
# Use Windows-1252, ISO-8859-1 or ISO-8859-15 if targeting ms excel
# (excel does not recognize utf8 encoded csv)
data.export.encoding = UTF-8

# whether to export collections fields
data.export.collections.enabled = true

# export separator for collections fields
data.export.collections.separator = \u0020|\u0020

# Specify whether to import demo data
# ~~~~~
data.import.demo-data = true

# Storage path for templates
# ~~~~~
template.search-dir = {user.home}/.axelor/templates

# Quartz Scheduler
# ~~~~~
# quartz job scheduler

# Specify whether to enable quartz scheduler
quartz.enable = true

# total number of threads in quartz thread pool
# the number of jobs that can run simultaneously
quartz.thread-count = 3

# Use JobStoreTX for persistence instead of default `org.quartz.simpl.RAMJobStore`
# Automatically enabled when setting `application.cache.provider` to a distributed cache provider
quartz.job-store.class = org.quartz.impl.jdbcjobstore.JobStoreTX

# Frequency (in milliseconds) at which an instance "checks-in" with the other instances of the cluster
quartz.job-store.cluster-checkin-interval = 7500

# Maximum number of connections that the DataSource can create in its pool of connections (defaults to `quartz.thread-count`)
quartz.data-source.maximum-pool-size = 3

# View configuration
# ~~~~~

# Menu style (left, top, both)
view.menubar.location = both

# Whether to show  confirm/cancel buttons from grid row editor
view.grid.editor-buttons = false

# Whether to disable views customization
view.allow-customization = true

# API
# ~~~~~

# Define the maximum number of items per page
api.pagination.max-per-page = 1000

# Global logging
logging.level.root = ERROR

# Axelor logging

# Log everything.
logging.level.com.axelor = DEBUG
